# input( )

## Definition and Usage

The input() function allows user input.

## Example

In [1]:
print('Enter your name:')
x = input()
print('Hello, ' + x)

Enter your name:
Erika
Hello, Erika


In [2]:
N = input();

Hi!


##  Syntax

input(prompt)

## Parameter Values

Parameter: prompt	
Description: A String, representing a default message before the input.

In [17]:
N = input();

map = {}

for i in range(int(N)):
    S = input().split();
    lst = (float(S[1]) + float(S[2]) + float(S[3]))/(len(S)-1);
    map[S[0]] = lst;
    
print("%0.2f"%map[input()]); # '%0.2f' Is the format to print just 2 decimals instead of all of them when you print a float


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


In [22]:
import numpy

n = int(input())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
print(numpy.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [28]:
import numpy

n = int(input())
a = numpy.array([input().split() for i in range(n)],int)
b = numpy.array([input().split() for i in range(n)],int)
print(numpy.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [27]:
n = int(input())
a = numpy.array([input().split() for i in range(n)], int)
print(a)

2
1 2
3 4
[[1 2]
 [3 4]]


In [29]:
import numpy

A = numpy.array(input().split(),int)
B = numpy.array(input().split(),int)

print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [51]:
import numpy

P = [float(num) for num in input().split()]
x = int(input())

print(numpy.polyval(P, x))

1.1 2 3
0
3.0


https://www.hackerrank.com/challenges/np-linear-algebra/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [60]:
# 2
# 1.1 1.1
# 1.1 1.1

In [64]:
import numpy

N = int(input())
A = numpy.array([input().split() for i in range(N)], float)

print(round(numpy.linalg.det(A), 2))

2
1.1 1.1
1.1 1.1
0.0


In [63]:
import numpy

N = int(input())
A = numpy.array([input().split() for i in range(N)], float)

print(round(numpy.linalg.det(A), 2))

2
1.1 1.1
1.1 1.2
0.11


https://www.hackerrank.com/challenges/itertools-product/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

In [65]:
# 1 2
# 3 4


# (1, 3) (1, 4) (2, 3) (2, 4)

In [76]:
from itertools import product

A=list(map(int, input().split(' ')))
B=list(map(int, input().split(' ')))

print(A)
print(B)

#print(list(product(A, B)))

1 2


TypeError: 'dict' object is not callable

In [ ]:
list(map(int, test_list)) 